---
- name: kube-backup | Copying templates
  template: src={{ item }} dest=/opt/ark/
  with_items:
    - 00-prereqs.yaml
    - 00-minio-deployment.yaml
    - 05-backupstoragelocation.yaml
    - 20-ark-deployment.yaml
    - 30-restic-daemonset.yaml
 
- name: kube-backup | Apply prereq ark
  shell: kubectl apply -f /opt/ark/00-prereqs.yaml ; sleep 2
  ignore_errors: true

- name: kube-backup | Apply ark-setup yaml
  shell: kubectl apply -f /opt/ark/{{ item }}
  with_items:
    - 00-minio-deployment.yaml
    - 05-backupstoragelocation.yaml
    - 20-ark-deployment.yaml
    - 30-restic-daemonset.yaml
  ignore_errors: true
