kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: istio-grafana-pvc
  namespace: istio-system
  labels:
    app: istio-grafana
    chart: grafana-1.1.2
    release: istio
    heritage: Tiller
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
