kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "{{ kubernetes_kube_proxy_dir }}/kube-proxy.kubeconfig"
mode: "iptables"
clusterCIDR: "{{ kubernetes_cluster_cidr }}"
