---
- name: metallb | copying template
  template:
    src: "{{ item }}"
    dest: /tmp/
  with_items:
    - metallb.yaml
    - metallb_configmap.yaml
  when:
    - k8s_master_main|bool


- name: metallb | installing
  shell: "kubectl apply -f /tmp/{{ item }}"
  with_items:
    - metallb.yaml
    - metallb_configmap.yaml
  ignore_errors: true
  when:
    - k8s_master_main|bool


- name: metallb | generating memberlist
  shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  ignore_errors: true
  when:
    - k8s_master_main|bool
