---
- name: metrics-server | install
  shell: "kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.7/components.yaml"
  ignore_errors: true
  when:
    - k8s_master_main|bool
