---
- name: control-plane | install binaries
  get_url:
    url: "{{ kubernetes_install_url }}/{{ item }}"
    dest: /usr/bin/
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl
  when: deploy_control_plane


- name: control-plane | create dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ kubernetes_dir }}"
    - /var/log/kubernetes
    - /var/run/kubernetes
