---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart kube-apiserver
  systemd: name=kube-apiserver.service state=restarted daemon_reload=yes

- name: restart kube-scheduler
  systemd: name=kube-scheduler.service state=restarted daemon_reload=yes

- name: restart kube-controller-manager
  systemd: name=kube-controller-manager.service state=restarted daemon_reload=yes
