---
- name: fetch_sslcert | fetching ssl certificates for controller nodes
  fetch:
    src: "{{ kubernetes_setup_dir }}/{{ item }}"
    dest: "{{ temporal_dir_sslcert }}/"
    flat: yes
  with_items:
    - ca.pem 
    - ca-key.pem
    - kubernetes.pem
    - kubernetes-key.pem 
    - admin.pem
    - admin-key.pem
    - kube-controller-manager.pem
    - kube-controller-manager-key.pem
    - kube-proxy.pem
    - kube-proxy-key.pem
    - kube-scheduler.pem
    - kube-scheduler-key.pem
    - service-account.pem
    - service-account-key.pem
  when:
    - k8s_master_main



- name: fetch_sslcert | fetching ssl certificates for worker nodes
  fetch:
    src: "{{ kubernetes_setup_dir }}/{{ item }}.pem"
    dest: "{{ temporal_dir_sslcert }}/"
    flat: yes
  with_items: "{{ groups['new_nodes'] }}"
  when:
    - k8s_master_main



- name: fetch_sslcert | fetching ssl key for worker nodes
  fetch:
    src: "{{ kubernetes_setup_dir }}/{{ item }}-key.pem"
    dest: "{{ temporal_dir_sslcert }}/"
    flat: yes
  with_items: "{{ groups['new_nodes'] }}"
  when:
    - k8s_master_main
