---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent


- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap'
    state: absent


- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
